-- 0002 down — reverse of 0002_create_price_aggregates.up.sql.

BEGIN;

-- MATERIALIZED VIEW drop cascades its policies + index.
DROP MATERIALIZED VIEW IF EXISTS prices_1mo;
DROP MATERIALIZED VIEW IF EXISTS prices_1w;
DROP MATERIALIZED VIEW IF EXISTS prices_1d;
DROP MATERIALIZED VIEW IF EXISTS prices_4h;
DROP MATERIALIZED VIEW IF EXISTS prices_1h;
DROP MATERIALIZED VIEW IF EXISTS prices_15m;
DROP MATERIALIZED VIEW IF EXISTS prices_1m;

COMMIT;
