/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness — process is up. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alive. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness — all dependencies reachable. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready to serve. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description Dependencies unreachable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Build metadata. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Version string, build date, git SHA. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VersionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List indexed assets.
         * @description Paginated list of every asset that has appeared (as base or
         *     quote) in the trades hypertable. Cursor is opaque; limit
         *     clamped server-side to [1, 500].
         *
         *     The `type` / `code` / `issuer` filter params are planned but
         *     not yet implemented — the current handler ignores any filter
         *     params and returns the unfiltered page. See the TypeFilter,
         *     CodeFilter, IssuerFilter schemas below for the planned
         *     shape; they are not wired to any request until the filter
         *     path ships.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Opaque pagination token echoed from a prior response's
                     *     `pagination.next`. Pass it verbatim — it is a base64url-encoded
                     *     blob whose internal shape is an implementation detail and
                     *     changes without notice. Clients MUST NOT parse, decode, or
                     *     construct cursors by hand.
                     *
                     *     A cursor is stable across retries but not across schema
                     *     changes; treat it as short-lived (minutes, not days). Empty
                     *     means "start from the beginning".
                     */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of assets. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssetListEnvelope"];
                    };
                };
                400: components["responses"]["BadRequest"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Asset detail. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Canonical asset identifier. One of `native`, `<code>-<issuer>`,
                     *     `<code>:<issuer>` (alias), or `<contract_id>`. Strkeys
                     *     validated per SEP-23.
                     */
                    asset_id: components["parameters"]["AssetIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Asset + metadata. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssetEnvelope"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{asset_id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Extended metadata (SEP-1 CURRENCIES block). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Canonical asset identifier. One of `native`, `<code>-<issuer>`,
                     *     `<code>:<issuer>` (alias), or `<contract_id>`. Strkeys
                     *     validated per SEP-23.
                     */
                    asset_id: components["parameters"]["AssetIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Extended metadata. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssetMetadataEnvelope"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current aggregated price for one asset. */
        get: {
            parameters: {
                query: {
                    /**
                     * @description Canonical asset identifier — matches the `asset_id` on
                     *     response bodies. Query-parameter form is the shorter `asset`
                     *     per the handler implementations (/v1/price, /v1/oracle/latest).
                     */
                    asset: components["parameters"]["AssetQuery"];
                    /** @description ISO-4217 fiat or crypto asset_id. Default `USD`. */
                    quote?: components["parameters"]["Quote"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current price with freshness flags. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PriceEnvelope"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/price/tip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rolling-window tip price (ADR-0018 tip surface).
         * @description Realtime "what's the price right now" surface per ADR-0018.
         *     Returns a VWAP over a short rolling window (default 5 s, clamp
         *     1–60 s); when the window has no trades, falls back to the
         *     most-recent observed price for the pair.
         *
         *     Both branches are **in-contract** — `flags.stale` is always
         *     `false` on this surface. Customers read `price_type` and
         *     `observed_at` to know what they got. Cross-region consistency
         *     is **not** provable here; use `/v1/price` for the closed-bucket
         *     guarantee.
         *
         *     URL discipline: `?granularity=` is rejected with 400 — that's
         *     a closed-bucket concept and accepting it would silently change
         *     the consistency contract.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description Canonical asset identifier — matches the `asset_id` on
                     *     response bodies. Query-parameter form is the shorter `asset`
                     *     per the handler implementations (/v1/price, /v1/oracle/latest).
                     */
                    asset: components["parameters"]["AssetQuery"];
                    /** @description ISO-4217 fiat or crypto asset_id. Default `USD`. */
                    quote?: components["parameters"]["Quote"];
                    /** @description Rolling-window size in seconds for the VWAP. */
                    window_seconds?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tip price (VWAP or last-good fallback). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PriceEnvelope"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/price/tip/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE stream of tip-price updates (ADR-0018).
         * @description Server-Sent Events counterpart of `/v1/price/tip`. Same
         *     compute logic; pushed on a per-connection tick (default
         *     every `window_seconds` seconds, clamp 1–60 s).
         *
         *     - First event fires synchronously on connect (no waiting a
         *       full window).
         *     - Pre-flight 404 when the pair has no observations: SSE
         *       can't change status mid-stream, so emptiness is detected
         *       before the response body switches to `text/event-stream`.
         *     - Heartbeats every 15 s as comment lines (`:keepalive`) so
         *       intermediate proxies don't idle out the connection.
         *     - Resume after disconnect by setting `Last-Event-ID` on the
         *       reconnect (header preferred, `?last_event_id=` fallback).
         *     - Same URL-discipline rule as `/v1/price/tip`:
         *       `?granularity=` returns 400.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description Canonical asset identifier — matches the `asset_id` on
                     *     response bodies. Query-parameter form is the shorter `asset`
                     *     per the handler implementations (/v1/price, /v1/oracle/latest).
                     */
                    asset: components["parameters"]["AssetQuery"];
                    /** @description ISO-4217 fiat or crypto asset_id. Default `USD`. */
                    quote?: components["parameters"]["Quote"];
                    /** @description Tick cadence (and rolling-VWAP window) in seconds. */
                    window_seconds?: number;
                };
                header?: {
                    /** @description Opaque ID for resuming a previously-broken stream. */
                    "Last-Event-ID"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE stream of tip_update events. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/price/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current prices for up to 100 assets. */
        get: {
            parameters: {
                query: {
                    /** @description Comma-separated, max 100. */
                    asset_ids: string;
                    /** @description ISO-4217 fiat or crypto asset_id. Default `USD`. */
                    quote?: components["parameters"]["Quote"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Batch prices. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PriceBatchEnvelope"];
                    };
                };
            };
        };
        put?: never;
        /** Current prices for up to 1000 assets. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        asset_ids: string[];
                        /** @default USD */
                        quote?: string;
                    };
                };
            };
            responses: {
                /** @description Batch prices. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PriceBatchEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Raw per-source observations (ADR-0018 Surface 3).
         * @description Lowest-level surface per ADR-0018: returns the most-recent
         *     trade from each source that has ever traded the (asset, quote)
         *     pair. No aggregation, no chaining, no smoothing — purely
         *     "what each venue last published".
         *
         *     - `?source=X` narrows to a single source (0- or 1-element array).
         *     - `?aggregate=latest` collapses to the single newest trade across
         *       sources (preserves the array wire shape; length 1).
         *     - `flags.stale` is **always** `false` here — there is no
         *       aggregation contract to fall short of.
         *     - Cross-region consistency is **NOT** provable on this surface;
         *       use `/v1/price` for the closed-bucket guarantee.
         *     - Empty pair returns 200 with `data: []`, not 404.
         *
         *     URL discipline: `?granularity=` and `?window_seconds=` return 400
         *     — those are closed-bucket and tip concepts respectively.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description Canonical asset identifier — matches the `asset_id` on
                     *     response bodies. Query-parameter form is the shorter `asset`
                     *     per the handler implementations (/v1/price, /v1/oracle/latest).
                     */
                    asset: components["parameters"]["AssetQuery"];
                    /** @description ISO-4217 fiat or crypto asset_id. Default `USD`. */
                    quote?: components["parameters"]["Quote"];
                    /** @description Restrict to one source's most-recent trade (0/1 row). */
                    source?: string;
                    /**
                     * @description `latest` collapses to the single most-recent trade across
                     *     all sources. Omit for one row per source.
                     */
                    aggregate?: "latest";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Per-source observations array. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnvelopeMeta"] & {
                            data: components["schemas"]["TradeRow"][];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalError"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/observations/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE stream of raw per-source observations (ADR-0018).
         * @description Streaming counterpart of `/v1/observations`. Same compute
         *     logic; pushed on a per-connection tick (default every 5 s,
         *     clamp 1–60 s — independent of tip's `window_seconds` because
         *     observations does not aggregate).
         *
         *     - First event fires synchronously on connect; data may be
         *       an empty array (the pair has no observations yet — same
         *       200/empty contract as the request endpoint, NOT 404).
         *     - Recurring events fire unconditionally on each tick (no
         *       server-side dedupe) — clients diff against the previous
         *       payload if they want change-detection.
         *     - Heartbeats every 15 s as comment lines.
         *     - URL discipline: `?granularity=` and `?window_seconds=`
         *       return 400.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description Canonical asset identifier — matches the `asset_id` on
                     *     response bodies. Query-parameter form is the shorter `asset`
                     *     per the handler implementations (/v1/price, /v1/oracle/latest).
                     */
                    asset: components["parameters"]["AssetQuery"];
                    /** @description ISO-4217 fiat or crypto asset_id. Default `USD`. */
                    quote?: components["parameters"]["Quote"];
                    /** @description Restrict to one source's most-recent trade. */
                    source?: string;
                    /**
                     * @description `latest` collapses to the single most-recent trade across
                     *     all sources.
                     */
                    aggregate?: "latest";
                    /** @description Tick cadence in seconds. */
                    interval_seconds?: number;
                };
                header?: {
                    /** @description Opaque ID for resuming a previously-broken stream. */
                    "Last-Event-ID"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE stream of observations_update events. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalError"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/price/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE stream of closed-bucket price updates (ADR-0015).
         * @description SSE counterpart of `/v1/price` — carries the strict ADR-0015
         *     closed-bucket consistency contract. Unlike `/v1/price/tip/stream`
         *     and `/v1/observations/stream` (per-connection tick), this
         *     surface is **Hub-driven**: the aggregator publishes one event
         *     per closed bucket, and every subscriber on the same
         *     (asset, quote) pair receives byte-identical payloads — the
         *     same cross-region consistency guarantee `/v1/price` exposes.
         *
         *     - Heartbeats every 15 s as comment lines.
         *     - Resume after disconnect via `Last-Event-ID` (header preferred,
         *       `?last_event_id=` fallback).
         *     - URL discipline: `?granularity=` returns 400 — the closed-
         *       bucket stream is fixed at 1m; use
         *       `/v1/history/since-inception` for other granularities.
         *     - 503 when the deployment hasn't wired the streaming Hub
         *       (typical pre-aggregator state).
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description Canonical asset identifier — matches the `asset_id` on
                     *     response bodies. Query-parameter form is the shorter `asset`
                     *     per the handler implementations (/v1/price, /v1/oracle/latest).
                     */
                    asset: components["parameters"]["AssetQuery"];
                    /** @description ISO-4217 fiat or crypto asset_id. Default `USD`. */
                    quote?: components["parameters"]["Quote"];
                };
                header?: {
                    /** @description Opaque ID for resuming a previously-broken stream. */
                    "Last-Event-ID"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE stream of price_update events. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                400: components["responses"]["BadRequest"];
                429: components["responses"]["RateLimited"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Raw trade history for a pair in a time window.
         * @description Returns per-trade records ordered (ts, ledger, tx_hash, op_index, source)
         *     ascending. Cursor paginates across the full-PK tuple; truncating
         *     the cursor at (ts, ledger) would drop rows sharing those
         *     values (high-volume ledgers).
         *
         *     Bucketed/granularity-based history (VWAP/TWAP series at 1m/15m/...)
         *     will ship via the aggregator binary (see
         *     cmd/ratesengine-aggregator) on a different response shape —
         *     not this endpoint.
         */
        get: {
            parameters: {
                query: {
                    /** @description Canonical asset identifier for the base side of a pair. */
                    base: components["parameters"]["Base"];
                    /** @description ISO-4217 fiat or crypto asset_id. Default `USD`. */
                    quote?: components["parameters"]["Quote"];
                    from?: components["parameters"]["From"];
                    to?: components["parameters"]["To"];
                    limit?: number;
                    /**
                     * @description Opaque pagination token echoed from a prior response's
                     *     `pagination.next`. Pass it verbatim — it is a base64url-encoded
                     *     blob whose internal shape is an implementation detail and
                     *     changes without notice. Clients MUST NOT parse, decode, or
                     *     construct cursors by hand.
                     *
                     *     A cursor is stable across retries but not across schema
                     *     changes; treat it as short-lived (minutes, not days). Empty
                     *     means "start from the beginning".
                     */
                    cursor?: components["parameters"]["Cursor"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Per-trade records. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TradeHistoryEnvelope"];
                    };
                };
                400: components["responses"]["BadRequest"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/since-inception": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Closed-bucket historical VWAP series for one asset/quote pair.
         * @description Returns every CLOSED bucket from the requested continuous
         *     aggregate ladder (`1m`, `15m`, `1h`, `4h`, `1d`, `1w`,
         *     `1mo`) for the requested asset/quote pair. This is the
         *     bucketed history surface; `/history` remains the raw
         *     per-trade endpoint.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description Canonical asset identifier — matches the `asset_id` on
                     *     response bodies. Query-parameter form is the shorter `asset`
                     *     per the handler implementations (/v1/price, /v1/oracle/latest).
                     */
                    asset: components["parameters"]["AssetQuery"];
                    /** @description ISO-4217 fiat or crypto asset_id. Default `USD`. */
                    quote?: components["parameters"]["Quote"];
                    granularity?: components["parameters"]["Granularity"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Since-inception series. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HistoryEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rolling-window chart series matching the Freighter RFP shape.
         * @description Returns CLOSED CAGG buckets within a rolling time window for
         *     one asset/quote pair, shaped as `(timeframe, granularity,
         *     price_type) → points[]` per the Freighter RFP V1 chart
         *     contract.
         *
         *     Defaults: `quote=fiat:USD`, `timeframe=24h`,
         *     `granularity` per the timeframe table below, `price_type=vwap`.
         *
         *     Default-granularity table (per ADR-0020):
         *
         *     | Timeframe | Default granularity |
         *     | --------- | ------------------- |
         *     | `1h`      | `1m`                |
         *     | `24h`     | `15m`               |
         *     | `1w`      | `1h`                |
         *     | `1mo`     | `4h`                |
         *     | `1y`      | `1d`                |
         *     | `all`     | `1d`                |
         *
         *     `price_type=twap` returns 400 — multi-bar TWAP charts are
         *     deferred to L7.8 (post-launch), see ADR-0020. Single-bar
         *     TWAP is available now via `/v1/twap` (true time-weighted
         *     compute from raw trades); only the multi-bar chart variant
         *     is the deferred surface.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description Canonical asset identifier — matches the `asset_id` on
                     *     response bodies. Query-parameter form is the shorter `asset`
                     *     per the handler implementations (/v1/price, /v1/oracle/latest).
                     */
                    asset: components["parameters"]["AssetQuery"];
                    /** @description ISO-4217 fiat or crypto asset_id. Default `USD`. */
                    quote?: components["parameters"]["Quote"];
                    timeframe?: components["parameters"]["Timeframe"];
                    granularity?: components["parameters"]["Granularity"];
                    price_type?: components["parameters"]["PriceType"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Chart series. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChartEnvelope"];
                    };
                };
                400: components["responses"]["BadRequest"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ohlc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Single OHLC bar for a pair over a window.
         * @description Single-bar response for the window [from, to). Interval-series
         *     (N bars, each interval-seconds wide) is a follow-up —
         *     delivered via the aggregator's continuous-aggregate path.
         *
         *     Defaults: `from = to - 1h`, `to = now`. `truncated=true` on
         *     the response means the window had more trades than the
         *     server's per-request cap (10000) and the bar reflects only
         *     the chronologically-first N; narrow the window or wait for
         *     CAGG-backed endpoints.
         */
        get: {
            parameters: {
                query: {
                    /** @description Canonical asset identifier for the base side of a pair. */
                    base: components["parameters"]["Base"];
                    /** @description ISO-4217 fiat or crypto asset_id. Default `USD`. */
                    quote?: components["parameters"]["Quote"];
                    from?: components["parameters"]["From"];
                    to?: components["parameters"]["To"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Single OHLC bar. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OHLCEnvelope"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vwap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Volume-weighted average price over a window.
         * @description Returns VWAP = Σ(quote) / Σ(base) for every trade in
         *     [from, to) for the given pair. Optional outlier filter
         *     drops prices > N σ from the window mean. When the window
         *     has more than the server's per-request cap (10000 trades)
         *     the response carries `truncated: true` — the price
         *     reflects only the chronologically-first N trades, not the
         *     full window.
         */
        get: {
            parameters: {
                query: {
                    /** @description Canonical asset identifier for the base side of a pair. */
                    base: components["parameters"]["Base"];
                    /** @description ISO-4217 fiat or crypto asset_id. Default `USD`. */
                    quote?: components["parameters"]["Quote"];
                    from?: components["parameters"]["From"];
                    to?: components["parameters"]["To"];
                    /** @description Drop trades > N σ from window mean. 0 disables (default). */
                    outlier_sigma?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Volume-weighted price + volumes + trade count. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VWAPEnvelope"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description No trades in window. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                /** @description All trades filtered as outliers. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/twap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Time-weighted average price over a window.
         * @description Each trade's price is active from its timestamp to the
         *     next trade's (or windowEnd for the last). TWAP is the
         *     duration-weighted mean. No outlier filter: time-weighting
         *     is itself outlier-resistant (spurious prints get only
         *     their slot duration, not a full window's worth).
         */
        get: {
            parameters: {
                query: {
                    /** @description Canonical asset identifier for the base side of a pair. */
                    base: components["parameters"]["Base"];
                    /** @description ISO-4217 fiat or crypto asset_id. Default `USD`. */
                    quote?: components["parameters"]["Quote"];
                    from?: components["parameters"]["From"];
                    to?: components["parameters"]["To"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Time-weighted price + trade count. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TWAPEnvelope"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description No trades in window. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oracle/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest oracle reading per source for an asset.
         * @description Returns one OracleReading per source (reflector-dex /
         *     reflector-cex / reflector-fx / redstone / band) that has
         *     observed the asset. Optional source filter restricts to a
         *     single source.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description Canonical asset identifier — matches the `asset_id` on
                     *     response bodies. Query-parameter form is the shorter `asset`
                     *     per the handler implementations (/v1/price, /v1/oracle/latest).
                     */
                    asset: components["parameters"]["AssetQuery"];
                    /** @description Optional. Restrict to a single source name. */
                    source?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of OracleReading (empty when no observations). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OracleLatestEnvelope"];
                    };
                };
                400: components["responses"]["BadRequest"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Distinct trading pairs with activity summary.
         * @description One entry per (base, quote) pair present in the trades
         *     store. Cursor-paginated (opaque cursor keyed on
         *     `<base>|<quote>`). Each entry reports the pair's most
         *     recent trade timestamp + a 24h trade count.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Opaque pagination token echoed from a prior response's
                     *     `pagination.next`. Pass it verbatim — it is a base64url-encoded
                     *     blob whose internal shape is an implementation detail and
                     *     changes without notice. Clients MUST NOT parse, decode, or
                     *     construct cursors by hand.
                     *
                     *     A cursor is stable across retries but not across schema
                     *     changes; treat it as short-lived (minutes, not days). Empty
                     *     means "start from the beginning".
                     */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of markets + optional next cursor. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MarketsEnvelope"];
                    };
                };
                400: components["responses"]["BadRequest"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Source catalogue with class + IncludeInVWAP metadata.
         * @description Static projection of the aggregator's source registry — every
         *     venue we know about, labelled with the class semantic that
         *     decides whether it contributes to VWAP. Sources with
         *     `include_in_vwap=false` are intentional policy
         *     (aggregator/oracle/authority_sanity classes), not missing
         *     connectors. Operators consult this endpoint to confirm a
         *     venue is recognised before debugging an absence in /v1/markets
         *     or /v1/vwap.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Optional class filter. When set, only sources of the
                     *     given class are returned. Useful for dashboards that
                     *     split the catalogue by role.
                     */
                    class?: "exchange" | "aggregator" | "oracle" | "authority_sanity";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of sources, sorted by name. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SourcesEnvelope"];
                    };
                };
                400: components["responses"]["BadRequest"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Direct markets for a pair. */
        get: {
            parameters: {
                query: {
                    base: string;
                    quote: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pairs. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PairsEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oracle/lastprice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SEP-40 lastprice-equivalent passthrough. */
        get: {
            parameters: {
                query: {
                    asset: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Price record. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OraclePriceEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oracle/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SEP-40 prices-equivalent passthrough (N historical). */
        get: {
            parameters: {
                query: {
                    asset: string;
                    records?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Historical records. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OraclePricesEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oracle/x_last_price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SEP-40 x_last_price-equivalent (cross-pair). */
        get: {
            parameters: {
                query: {
                    base: string;
                    quote: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cross-pair last price. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OraclePriceEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API-key holder info + quota status. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usage-summary placeholder (currently empty).
         * @description Placeholder self-service surface. The handler currently
         *     returns an empty list while the backing counter store is not
         *     implemented yet; `from` / `to` are reserved for the future
         *     implementation and are ignored today.
         */
        get: {
            parameters: {
                query?: {
                    from?: components["parameters"]["From"];
                    to?: components["parameters"]["To"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Usage records. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsageEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new API key.
         * @description Issues a new API key for the authenticated caller and returns
         *     the plaintext exactly once.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        label: string;
                    };
                };
            };
            responses: {
                /** @description New key — plaintext shown **once**. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KeyCreatedEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sep10/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SEP-10 Web Auth — issue a challenge transaction.
         * @description Returns a Stellar challenge transaction the client must sign
         *     with its account secret key. Per SEP-10 §3.2 the response
         *     carries the unsigned XDR + the network passphrase the
         *     challenge was crafted for. Unauthenticated by design.
         */
        get: {
            parameters: {
                query: {
                    /** @description Stellar G-strkey of the account being authenticated. */
                    account: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unsigned challenge transaction. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnvelopeMeta"] & {
                            data: components["schemas"]["SEP10Challenge"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sep10/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * SEP-10 Web Auth — exchange a signed challenge for a JWT.
         * @description Accepts a signed challenge transaction and returns a JWT
         *     bearing the authenticated G-strkey. Per SEP-10 §3.3 the body
         *     carries `{transaction: <base64-XDR>}`. Unauthenticated by
         *     design — the SEP-10 protocol IS the authentication.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Base64-encoded signed XDR of the challenge. */
                        transaction: string;
                    };
                };
            };
            responses: {
                /** @description Authenticated; JWT issued. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnvelopeMeta"] & {
                            data: components["schemas"]["SEP10Token"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Signature verification failed. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                /** @description Challenge time-bounds expired; request a fresh challenge. */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Advisory quality markers. See docs/architecture/ha-plan.md §9
         *     and ADR-0019 (anomaly detection / freeze policy).
         *
         *     - `stale` — response is below this surface's documented
         *       baseline contract.
         *     - `reduced_redundancy` — cross-region redundancy is degraded
         *       (R2/R3 set this when R1's last completeness run is stale
         *       per ADR-0017).
         *     - `triangulated` — set when the served price was derived
         *       via cross-pair multiplication (e.g. XLM/EUR computed from
         *       XLM/USD × USD/EUR) rather than direct trade observation.
         *       The aggregator's triangulation pass writes the implied
         *       VWAP into the same Redis key with a `:provenance` marker;
         *       `/v1/price` reads that marker and forwards the flag.
         *     - `divergence_warning` — anomaly check or cross-reference
         *       observed a meaningful divergence; treat with caution.
         *     - `frozen` — anomaly detection refused to publish the new
         *       bucket; this response carries the previous bucket's
         *       last-known-good value (ADR-0019). Only fires on `/v1/price`;
         *       tip + observations surfaces ignore freeze.
         *     - `single_source` — the bucket had only one contributing
         *       source. When `frozen=true` this is forced true (an LKG
         *       fallback is by definition single-sourced). Informational;
         *       combined with `frozen` this is the manipulation signature.
         */
        Flags: {
            /** @default false */
            stale: boolean;
            /** @default false */
            reduced_redundancy: boolean;
            /** @default false */
            triangulated: boolean;
            /** @default false */
            divergence_warning: boolean;
            /** @default false */
            frozen: boolean;
            /** @default false */
            single_source: boolean;
        };
        /**
         * @description Present on list endpoints when more rows exist beyond the
         *     current page. Absent on the final page — clients must detect
         *     "no more data" by checking for the absence of this object,
         *     not by parsing `next`.
         */
        Pagination: {
            /**
             * @description Opaque token to pass as the `cursor` query parameter on
             *     the next request. Base64url-encoded; contents are an
             *     implementation detail and change without notice. Clients
             *     MUST pass this value verbatim — do not decode or
             *     manipulate.
             */
            next?: string | null;
        };
        /** @description Every 2xx response carries these. */
        EnvelopeMeta: {
            /** Format: date-time */
            as_of: string;
            sources?: string[];
            flags: components["schemas"]["Flags"];
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "degraded";
        };
        VersionResponse: components["schemas"]["EnvelopeMeta"] & {
            data: {
                /** @description Human-readable git-describe (or `dev`). */
                version: string;
                /** @description ISO-8601 UTC build timestamp (or `unknown`). */
                build_date: string;
                /** @description Full VCS revision SHA from runtime/debug.BuildInfo (or `unknown`). */
                commit: string;
                /** @description `true` if the build tree had uncommitted changes; `false` otherwise. Production builds should always be `false`. */
                dirty: string;
                /** @description Runtime Go version (e.g. `go1.22.3`). */
                go_version: string;
            };
        };
        Asset: {
            asset_id: string;
            /** @enum {string} */
            type: "native" | "classic" | "soroban" | "fiat";
            code: string;
            issuer?: string | null;
            contract_id?: string | null;
            home_domain?: string | null;
            decimals: number;
            /**
             * @description State of the SEP-1 overlay for this asset.
             *     - not_applicable: no home-domain (native, fiat, SAC-only).
             *     - not_fetched:    has a home-domain but resolver wasn't wired.
             *     - verified:       SEP-1 fetched + matching [[CURRENCIES]] entry found.
             *     - no_match:       SEP-1 fetched but no matching issuer+code entry.
             *     - unreachable:    fetch / parse failed (see server logs).
             * @enum {string}
             */
            sep1_status: "not_applicable" | "not_fetched" | "verified" | "no_match" | "unreachable";
            name?: string | null;
            description?: string | null;
            image?: string | null;
            org_name?: string | null;
            anchor_asset?: string | null;
            anchor_asset_type?: string | null;
            /** @description Issuer's declared terms / conditions text. */
            conditions?: string | null;
            /** @description SEP-1-declared fixed total supply (decimal string in the asset's smallest integer unit). Distinct from `total_supply` below — that's the live-ledger sum. */
            fixed_number?: string | null;
            /** @description SEP-1-declared maximum supply ceiling (decimal string). Distinct from `max_supply` below which is operator/policy-derived. */
            max_number?: string | null;
            /** @description Issuer asserts unbounded issuance. Null when the issuer didn't address supply at all; false when they declared a bounded supply. */
            is_unlimited?: boolean | null;
            /** @description Raw integer in asset's smallest unit (per ADR-0011 supply derivation). Null when no snapshot exists. */
            circulating_supply?: string | null;
            /** @description Raw integer in asset's smallest unit. Null when no snapshot exists. */
            total_supply?: string | null;
            /** @description Raw integer in asset's smallest unit. Null for uncapped issuers without operator override or SEP-1 declaration. */
            max_supply?: string | null;
            /** @description circulating_supply × USD price / 10^decimals, two fractional digits. Null when supply or USD price is unavailable. */
            market_cap_usd?: string | null;
            /** @description max_supply × USD price / 10^decimals, two fractional digits. Null when max_supply is null or USD price unavailable. */
            fdv_usd?: string | null;
            /**
             * @description Which ADR-0011 policy produced the supply numbers.
             *     Surfaced so consumers can decide how much to trust the
             *     absolute value (e.g. `override` indicates an operator
             *     curated the locked-set or SEP-1 declared a max_supply;
             *     `issuer_exclusion`/`admin_exclusion` are algorithm
             *     defaults). Null when no supply snapshot is available.
             * @enum {string|null}
             */
            supply_basis?: "xlm_sdf_reserve_exclusion" | "issuer_exclusion" | "admin_exclusion" | "override" | null;
            /**
             * @description Trailing-24h USD-denominated trade volume across every
             *     pair this asset participates in (as base OR quote).
             *     Decimal string. "0" is a valid value (asset tracked, no
             *     trades in the window); null means the volume reader
             *     isn't wired or the lookup failed. Per Freighter V2
             *     scope ("24h Trading Volume aggregate across indexed
             *     markets").
             *
             *     **Scope caveat (launch-readiness L2.2):** off-chain
             *     CEX/FX trades populate `usd_volume` automatically when
             *     the quote is `fiat:USD` or a USD-pegged stablecoin
             *     (USDC / USDT / DAI / PYUSD / USDP).
             *
             *     On-chain DEX trades (Stellar SDEX, Soroswap, Aquarius,
             *     Phoenix, Comet) populate `usd_volume` when their quote
             *     asset is in the operator's
             *     `[trades].usd_pegged_classic_assets` allow-list, or its
             *     SAC contract is wired transitively via
             *     `[supply.sac_wrappers]` (L2.2 phase 1). Deployments
             *     that haven't configured the allow-list see on-chain
             *     trades contribute 0 — comparisons with external
             *     aggregators (CoinGecko, CMC) will read systematically
             *     lower until the operator opts in.
             *
             *     On-chain trades quoted in non-USD assets (XLM/AQUA,
             *     XLM/BTC, etc.) still contribute 0; the FX-anchor
             *     multiplication for non-USD on-chain quotes is L2.2
             *     phase 2, post-launch. The schema is forward-compatible:
             *     phase 2 lands additively without a wire-shape change.
             */
            volume_24h_usd?: string | null;
        };
        AssetEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: components["schemas"]["Asset"];
        };
        AssetListEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: components["schemas"]["Asset"][];
            pagination?: components["schemas"]["Pagination"];
        };
        /**
         * @description SEP-1 overlay re-projection of /v1/assets/{id}'s metadata
         *     slice. Same shape the asset-detail surface returns under
         *     the `name`/`description`/etc. keys, here without the
         *     ledger-derived F2 fields. Populated when the issuer
         *     publishes a stellar.toml whose [[CURRENCIES]] entry
         *     matches the asset's `(code, issuer)` — `sep1_status`
         *     then reads "verified". `not_applicable` (native, fiat,
         *     SAC-only), `not_fetched` (operator hasn't configured the
         *     home-domain map for this issuer), `unreachable` (fetch
         *     or parse failed), and `no_match` (TOML loaded but no
         *     matching currency block) leave the overlay fields null.
         */
        AssetMetadata: {
            asset_id: string;
            home_domain?: string | null;
            /** @enum {string} */
            sep1_status: "not_applicable" | "not_fetched" | "verified" | "no_match" | "unreachable";
            name?: string | null;
            description?: string | null;
            /** @description Issuer-supplied logo URL. http(s) only — non-http schemes are stripped at overlay time. */
            image?: string | null;
            org_name?: string | null;
            anchor_asset?: string | null;
            /** @description fiat / crypto / stock / etc., per SEP-1 §Currencies. */
            anchor_asset_type?: string | null;
            /** @description Issuer's declared terms / conditions text. */
            conditions?: string | null;
            /** @description SEP-1-declared fixed total supply (decimal string in the asset's smallest integer unit). Distinct from /v1/assets/{id}'s `total_supply` which is the live-ledger sum. */
            fixed_number?: string | null;
            /** @description SEP-1-declared maximum supply ceiling (decimal string). Distinct from /v1/assets/{id}'s `max_supply` which is operator/policy-derived. */
            max_number?: string | null;
            /** @description Issuer asserts unbounded issuance. Null when the issuer didn't address supply at all (no fixed_number / max_number / is_unlimited declaration); false when they did and committed to a bounded supply. */
            is_unlimited?: boolean | null;
        };
        AssetMetadataEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: components["schemas"]["AssetMetadata"];
        };
        Price: {
            asset_id: string;
            quote: string;
            /** @description Decimal string. Never JSON number. */
            price: string;
            /** @enum {string} */
            price_type: "vwap" | "twap" | "last_trade";
            /** Format: date-time */
            observed_at: string;
            /** @description Window size for vwap/twap; omitted for last_trade. */
            window_seconds?: number | null;
            /** @description Trailing-24h price change as a signed decimal percentage with two fractional digits (e.g. "+1.27", "-0.05", "0.00"). Computed as (now - then) / then * 100 against the latest closed prices_1m bucket whose end is at-or-before now-24h. Null when the asset has no current USD price OR no comparison bucket in the 24h-ago window. */
            change_24h_pct?: string | null;
            /** @description aggregator */
            volume_24h_usd?: string | null;
            /** @description aggregator + supply derivation */
            market_cap_usd?: string | null;
            /** @description aggregator + supply derivation */
            fdv_usd?: string | null;
            /** @description supply derivation */
            circulating_supply?: string | null;
            /** @description supply derivation */
            total_supply?: string | null;
            /** @description supply derivation */
            max_supply?: string | null;
            /**
             * Format: float
             * @description Multi-factor confidence score in [0, 1] (ADR-0019).
             */
            confidence?: number | null;
            /** @description Per-factor decomposition of confidence (ADR-0019). */
            confidence_factors?: {
                /** Format: float */
                z_score?: number;
                /** Format: float */
                source_count?: number;
                /** Format: float */
                diversity?: number;
                /** Format: float */
                liquidity?: number;
                /** Format: float */
                cross_oracle?: number;
                /** Format: float */
                baseline_quality?: number;
            } | null;
        };
        PriceEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: components["schemas"]["Price"];
        };
        PriceBatchEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: components["schemas"]["Price"][];
        };
        HistoryPoint: {
            /** Format: date-time */
            t: string;
            p: string;
            v_usd?: string | null;
        };
        HistoryEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: {
                asset_id: string;
                quote: string;
                /** @enum {string} */
                price_type: "vwap" | "twap";
                granularity: string;
                points: components["schemas"]["HistoryPoint"][];
            };
        };
        ChartEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: {
                asset_id: string;
                quote: string;
                /** @enum {string} */
                timeframe: "1h" | "24h" | "1w" | "1mo" | "1y" | "all";
                /** @enum {string} */
                granularity: "1m" | "15m" | "1h" | "4h" | "1d" | "1w" | "1mo";
                /** @enum {string} */
                price_type: "vwap" | "twap";
                points: components["schemas"]["HistoryPoint"][];
            };
        };
        TradeRow: {
            source: string;
            ledger: number;
            /** @description 64 lowercase hex chars. */
            tx_hash: string;
            op_index: number;
            /** Format: date-time */
            ts: string;
            base_asset: string;
            quote_asset: string;
            /** @description Integer stroops, decimal string. */
            base_amount: string;
            /** @description Integer stroops, decimal string. */
            quote_amount: string;
            /** @description quote/base, 10-digit decimal. */
            price: string;
        };
        TradeHistoryEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: components["schemas"]["TradeRow"][];
            pagination?: components["schemas"]["Pagination"];
        };
        OHLCBar: {
            /**
             * Format: date-time
             * @description Inclusive lower bound of the bar window. Like VWAPResult.from,
             *     see ADR-0015 for the closed-bucket clamp semantics that
             *     preserve cross-region rate equality.
             */
            from: string;
            /**
             * Format: date-time
             * @description Exclusive upper bound of the bar window. Clamped to a 30 s
             *     boundary when the request omitted `to`.
             */
            to: string;
            /** @description Decimal string, 10 digits. */
            open: string;
            high: string;
            low: string;
            close: string;
            /** @description Σ base_amount integer stroops. */
            base_volume: string;
            /** @description Σ quote_amount integer stroops. */
            quote_volume: string;
            trade_count: number;
            /** @description True when window exceeded the per-request trade cap; bar reflects only the first N. */
            truncated: boolean;
        };
        OHLCEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: components["schemas"]["OHLCBar"];
        };
        VWAPResult: {
            /**
             * Format: date-time
             * @description Inclusive lower bound of the window the rate covers.
             *     Used as part of the as_of identity for cross-region rate
             *     equality (ADR-0015).
             */
            from: string;
            /**
             * Format: date-time
             * @description Exclusive upper bound of the window. When the request
             *     omitted `to`, this is clamped down to a 30-second
             *     boundary so two parallel requests in the same window
             *     return identical responses across regions. When the
             *     request supplied `to` explicitly, this echoes the
             *     request value.
             */
            to: string;
            /** @description VWAP decimal, 10 digits. */
            price: string;
            base_volume: string;
            quote_volume: string;
            trade_count: number;
            outliers_filtered: number;
            truncated: boolean;
        };
        VWAPEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: components["schemas"]["VWAPResult"];
        };
        TWAPResult: {
            /**
             * Format: date-time
             * @description Inclusive lower bound of the window. See VWAPResult.from
             *     and ADR-0015 for the closed-bucket clamp semantics.
             */
            from: string;
            /**
             * Format: date-time
             * @description Exclusive upper bound of the window. Clamped to a 30 s
             *     boundary when the request omitted `to`. See VWAPResult.to.
             */
            to: string;
            /** @description TWAP decimal, 10 digits. */
            price: string;
            trade_count: number;
            truncated: boolean;
        };
        TWAPEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: components["schemas"]["TWAPResult"];
        };
        OracleReading: {
            /** @description e.g. reflector-dex, reflector-cex, reflector-fx. */
            source: string;
            /** @description C-strkey, omitted for off-chain sources. */
            contract_id?: string;
            asset: string;
            quote: string;
            /** Format: date-time */
            ts: string;
            /** @description Decimal string at declared decimals scale. */
            price: string;
            /** @description Raw integer value preserved for cross-check (ADR-0003). */
            price_raw: string;
            decimals: number;
            /** @description 0 means unreported, not zero-confidence. */
            confidence?: number;
            /** @description G-strkey of the publishing account; empty when unknown. */
            observer?: string;
        };
        OracleLatestEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: components["schemas"]["OracleReading"][];
        };
        MarketRow: {
            base: string;
            quote: string;
            /** Format: date-time */
            last_trade_at: string;
            /** @description Activity count in the trailing 24h window. */
            trade_count_24h: number;
        };
        MarketsEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: components["schemas"]["MarketRow"][];
            pagination?: components["schemas"]["Pagination"];
        };
        Source: {
            /** @description Stable connector identifier (matches canonical.Trade.Source). */
            name: string;
            /**
             * @description Top-level taxonomy. Drives the aggregator's class filter — only `exchange` contributes to VWAP by default.
             * @enum {string}
             */
            class: "exchange" | "aggregator" | "oracle" | "authority_sanity";
            /**
             * @description Refines `class=exchange` for UIs that group venues. Empty (omitted) for non-exchange classes.
             * @enum {string}
             */
            subclass?: "dex" | "cex" | "fx";
            /** @description Whether this source's trades contribute to VWAP. */
            include_in_vwap: boolean;
            /** @description Whether this connector requires a paid licence / API key. */
            paid: boolean;
            /** @description Whether the source supports historical backfill via its native API. */
            backfill_available: boolean;
            /** @description Whether `ratesengine-ops backfill` will run on this source. On-chain Soroban sources start `false` and only flip `true` after a per-WASM-hash audit (`docs/operations/wasm-audits/`); off-chain CEX/FX sources are always `true`. */
            backfill_safe: boolean;
            /** @description Default per-source weight for weighted-aggregation paths (when those land). */
            default_weight: number;
        };
        SourcesEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: components["schemas"]["Source"][];
        };
        PairsEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: components["schemas"]["MarketRow"][];
        };
        OraclePriceEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: {
                asset: string;
                price: string;
                /** Format: date-time */
                timestamp: string;
            };
        };
        OraclePricesEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: {
                price: string;
                /** Format: date-time */
                timestamp: string;
            }[];
        };
        Account: {
            key_id?: string;
            label?: string;
            /** @enum {string} */
            tier?: "anonymous" | "apikey" | "partner";
            rate_limit_per_min?: number;
            /** Format: date-time */
            created_at?: string;
        };
        AccountEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: components["schemas"]["Account"];
        };
        UsageRow: {
            /** Format: date */
            date?: string;
            requests?: number;
            errors?: number;
            throttled?: number;
        };
        UsageEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: components["schemas"]["UsageRow"][];
        };
        KeyCreatedEnvelope: components["schemas"]["EnvelopeMeta"] & {
            data: {
                key_id: string;
                /** @description Shown once. Store it now. */
                plaintext: string;
                label: string;
            };
        };
        SEP10Challenge: {
            /** @description Base64-encoded XDR of the unsigned challenge transaction. Field name per SEP-10 §3.2. */
            transaction: string;
            /** @description Stellar network the challenge was crafted for (echoed so clients verify before signing). Per SEP-10 §3.2. */
            network_passphrase: string;
            /** Format: date-time */
            issued_at: string;
            /** Format: date-time */
            valid_until: string;
        };
        SEP10Token: {
            /** @description JWT bearer the client sends as `Authorization` on subsequent requests. */
            token: string;
            /** Format: date-time */
            expires_at: string;
            /** @description G-strkey of the authenticated account; convenience for clients that don't decode the JWT. */
            account: string;
        };
        /**
         * @description RFC 9457 problem details. Custom extension fields are snake_case.
         *     `request_id` echoes the X-Request-ID response header so a
         *     client bug report containing only the body is enough for
         *     support to correlate against server logs.
         */
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @description Mirror of the X-Request-ID response header. */
            request_id?: string;
        };
    };
    responses: {
        /** @description Not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Client-supplied parameters didn't validate. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate-limit quota exhausted. See `Retry-After` header. */
        RateLimited: {
            headers: {
                /** @description Seconds until the caller can retry. */
                "Retry-After"?: number;
                "X-RateLimit-Limit"?: number;
                "X-RateLimit-Remaining"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Internal error. Body includes the request_id for correlation. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Server is degraded (dependency outage, startup, shutdown). */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /**
         * @description Canonical asset identifier. One of `native`, `<code>-<issuer>`,
         *     `<code>:<issuer>` (alias), or `<contract_id>`. Strkeys
         *     validated per SEP-23.
         */
        AssetIdPath: string;
        /**
         * @description Canonical asset identifier — matches the `asset_id` on
         *     response bodies. Query-parameter form is the shorter `asset`
         *     per the handler implementations (/v1/price, /v1/oracle/latest).
         */
        AssetQuery: string;
        /** @description ISO-4217 fiat or crypto asset_id. Default `USD`. */
        Quote: string;
        Timeframe: "1h" | "24h" | "1w" | "1mo" | "1y" | "all";
        Granularity: "1m" | "15m" | "1h" | "4h" | "1d" | "1w" | "1mo";
        /** @description Canonical asset identifier for the base side of a pair. */
        Base: string;
        From: string;
        To: string;
        PriceType: "vwap" | "twap";
        TypeFilter: "native" | "classic" | "soroban" | "fiat" | "any";
        CodeFilter: string;
        IssuerFilter: string;
        /**
         * @description Opaque pagination token echoed from a prior response's
         *     `pagination.next`. Pass it verbatim — it is a base64url-encoded
         *     blob whose internal shape is an implementation detail and
         *     changes without notice. Clients MUST NOT parse, decode, or
         *     construct cursors by hand.
         *
         *     A cursor is stable across retries but not across schema
         *     changes; treat it as short-lived (minutes, not days). Empty
         *     means "start from the beginning".
         */
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
