// scripts/ops/circulation-fetch — one-off World Bank fetcher.
//
// Queries the World Bank Indicator API (FM.LBL.BMNY.CN — broad
// money in current LCU) for the currencies missing from
// internal/sources/external/forex/circulation_data.csv and emits append-
// ready CSV rows to stdout.
//
// Usage:
//
//	go run ./scripts/ops/circulation-fetch > rows.csv
//
// Then operator review + paste the rows into the CSV. Annual data,
// so this is a once-a-year refresh, not a runtime dependency.
package main

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"
)

// currencyToCountry maps each currency the WB serves to its ISO
// 3166 alpha-3 country code. Eurozone and currency-union pairs
// (e.g. CFA franc) point at a representative country with the
// most-recent published series. Curated 2026-05-08.
var currencyToCountry = map[string]string{
	"ALL": "ALB", // Albania
	"ARS": "ARG", // Argentina
	"BAM": "BIH", // Bosnia
	"BBD": "BRB", // Barbados
	"BDT": "BGD", // Bangladesh
	"BHD": "BHR", // Bahrain
	"BIF": "BDI", // Burundi
	"BND": "BRN", // Brunei
	"BOB": "BOL", // Bolivia
	"BSD": "BHS", // Bahamas
	"BWP": "BWA", // Botswana
	"BZD": "BLZ", // Belize
	"COP": "COL", // Colombia
	"CRC": "CRI", // Costa Rica
	"CUP": "CUB", // Cuba
	"CVE": "CPV", // Cabo Verde
	"CZK": "CZE", // Czechia
	"DJF": "DJI", // Djibouti
	"DOP": "DOM", // Dominican Republic
	"DZD": "DZA", // Algeria
	"EGP": "EGY", // Egypt
	"ETB": "ETH", // Ethiopia
	"FJD": "FJI", // Fiji
	"GHS": "GHA", // Ghana
	"GNF": "GIN", // Guinea
	"GTQ": "GTM", // Guatemala
	"GYD": "GUY", // Guyana
	"HNL": "HND", // Honduras
	"HTG": "HTI", // Haiti
	"HUF": "HUN", // Hungary
	"IDR": "IDN", // Indonesia
	"IQD": "IRQ", // Iraq
	"ISK": "ISL", // Iceland
	"JMD": "JAM", // Jamaica
	"KES": "KEN", // Kenya
	"KHR": "KHM", // Cambodia
	"KWD": "KWT", // Kuwait
	"KYD": "CYM", // Cayman
	"KZT": "KAZ", // Kazakhstan
	"LAK": "LAO", // Laos
	"LBP": "LBN", // Lebanon
	"LKR": "LKA", // Sri Lanka
	"LRD": "LBR", // Liberia
	"LSL": "LSO", // Lesotho
	"LYD": "LBY", // Libya
	"MAD": "MAR", // Morocco
	"MDL": "MDA", // Moldova
	"MGA": "MDG", // Madagascar
	"MKD": "MKD", // North Macedonia
	"MOP": "MAC", // Macao
	"MUR": "MUS", // Mauritius
	"MWK": "MWI", // Malawi
	"MYR": "MYS", // Malaysia
	"NAD": "NAM", // Namibia
	"NGN": "NGA", // Nigeria
	"NIO": "NIC", // Nicaragua
	"NPR": "NPL", // Nepal
	"OMR": "OMN", // Oman
	"PAB": "PAN", // Panama
	"PEN": "PER", // Peru
	"PGK": "PNG", // Papua New Guinea
	"PHP": "PHL", // Philippines
	"PKR": "PAK", // Pakistan
	"PYG": "PRY", // Paraguay
	"QAR": "QAT", // Qatar
	"RON": "ROU", // Romania
	"RSD": "SRB", // Serbia
	"RWF": "RWA", // Rwanda
	"SAR": "SAU", // Saudi Arabia
	"SCR": "SYC", // Seychelles
	"SOS": "SOM", // Somalia
	"SVC": "SLV", // El Salvador
	"SZL": "SWZ", // Eswatini (Swaziland)
	"TJS": "TJK", // Tajikistan
	"TND": "TUN", // Tunisia
	"TTD": "TTO", // Trinidad
	"TZS": "TZA", // Tanzania
	"UAH": "UKR", // Ukraine
	"UGX": "UGA", // Uganda
	"UYU": "URY", // Uruguay
	"UZS": "UZB", // Uzbekistan
	"VND": "VNM", // Vietnam
	"XPF": "PYF", // CFP franc — French Polynesia (representative)
	"ZMW": "ZMB", // Zambia
	"CNH": "",    // Offshore CNY — no separate WB series; same as CNY
}

type wbDatum struct {
	Date    string  `json:"date"`
	Value   float64 `json:"value"`
	Country struct {
		Value string `json:"value"`
	} `json:"country"`
}

// fetchBroadMoney returns (value, year-string, ok).
// Picks the most-recent non-null annual observation in the past 5y.
func fetchBroadMoney(ctx context.Context, country string) (float64, string, bool) {
	url := fmt.Sprintf(
		"https://api.worldbank.org/v2/country/%s/indicator/FM.LBL.BMNY.CN?format=json&date=2019:2024&per_page=10",
		country,
	)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return 0, "", false
	}
	c := &http.Client{Timeout: 10 * time.Second}
	res, err := c.Do(req)
	if err != nil {
		return 0, "", false
	}
	defer func() { _ = res.Body.Close() }()
	body, _ := io.ReadAll(res.Body)
	// WB returns a tuple [meta, data]; some countries return [meta, null].
	var raw []json.RawMessage
	if err := json.Unmarshal(body, &raw); err != nil || len(raw) < 2 {
		return 0, "", false
	}
	var data []wbDatum
	if err := json.Unmarshal(raw[1], &data); err != nil {
		return 0, "", false
	}
	// WB returns most-recent first, but can have nulls; pick the
	// first non-zero value.
	for _, d := range data {
		if d.Value > 0 {
			return d.Value, d.Date, true
		}
	}
	return 0, "", false
}

func main() {
	tickers := make([]string, 0, len(currencyToCountry))
	for t := range currencyToCountry {
		tickers = append(tickers, t)
	}
	sort.Strings(tickers)

	w := bufio.NewWriter(os.Stdout)
	defer func() { _ = w.Flush() }()

	_, _ = fmt.Fprintln(w, "# Generated by scripts/ops/circulation-fetch on", time.Now().UTC().Format(time.RFC3339))
	_, _ = fmt.Fprintln(w, "# Source: World Bank Indicator API (FM.LBL.BMNY.CN — broad money, LCU).")
	_, _ = fmt.Fprintln(w, "# Annual cadence; refresh once a year by re-running this script.")
	_, _ = fmt.Fprintln(w, "# Rows where WB returned no data are commented out (preserved for visibility).")
	_, _ = fmt.Fprintln(w)

	hits := 0
	misses := 0
	for _, ticker := range tickers {
		country := currencyToCountry[ticker]
		if country == "" {
			_, _ = fmt.Fprintf(w, "# %s: no WB country mapping (offshore/peg/special). Skipped.\n", ticker)
			misses++
			continue
		}
		val, year, ok := fetchBroadMoney(context.Background(), country)
		if !ok {
			_, _ = fmt.Fprintf(os.Stderr, "  miss: %s (%s)\n", ticker, country)
			_, _ = fmt.Fprintf(w, "# %s: WB returned no data for %s in 2019-2024.\n", ticker, country)
			misses++
			continue
		}
		// Round to nearest integer LCU. WB returns floats but the
		// CSV format expects an integer.
		valStr := fmt.Sprintf("%.0f", val)
		// Strip trailing .0 noise (already gone via %.0f but defensive).
		valStr = strings.TrimSuffix(valStr, ".0")
		// Synthesize as_of YYYY-12-31 (WB annual data stamps end-of-year).
		asOf := year + "-12-31"
		_, _ = fmt.Fprintf(w, "%s,%s,%s,WorldBank:FM.LBL.BMNY.CN\n", ticker, valStr, asOf)
		hits++
		_, _ = fmt.Fprintf(os.Stderr, "  hit:  %s = %s LCU (%s)\n", ticker, valStr, year)
	}
	_, _ = fmt.Fprintf(os.Stderr, "\nDone: %d hits, %d misses (out of %d total)\n", hits, misses, len(tickers))
}
